version: "3.9"

services:
  store-manager:
    container_name: store-manager
    build:
      context: .
      dockerfile: containers/store-manager/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/code
    tty: true
    env_file:
      - .env.prod
  image-web:
    container_name: image-web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./static:/static
    ports:
      - 80:80
  ssl-web:
    container_name: ssl-web
    build:
      context: .
      dockerfile: containers/https-portal/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: 'tely-store.st.ie.u-ryukyu.ac.jp -> http://image-web:80'
      STAGE: 'production'
      #FORCE_RENEW: 'true'
    volumes:
      - ./containers/https-portal/ssl_certs:/var/lib/https-portal
    depends_on:
      - image-web
volumes:
  static:
