version: "3.9"

services:
  store-manager:
    container_name: store-manager
    build:
      context: .
      dockerfile: containers/store-manager/Dockerfile
    volumes:
      - .:/code
    tty: true
    env_file:
      - .env.dev
    networks:
      - shared_network
  image-web:
    container_name: image-web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - 80:80
    networks:
      - shared_network
volumes:
  static:

networks:
  shared_network:
    external: true
